---
postgresql_packages: postgresql
postgresql_python_library: postgresql-plpython3,python3-psycopg2
postgresql_data_dir: /var/pgsql/data
postgresql_user: postgres
postgresql_group: postgres
postgresql_bin_path: /usr/bin

