eureka:
  instance:
    health-check-url: /actuator/heath/
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5
logging:
  level:
    de:
      codecentric: DEBUG
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full

server:
  port: 8110
spring:
  application:
    name: mano-geo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm
          jwk-set-uri: http://auth.mano.ubiqube.com/auth/realms/mano-realm/protocol/openid-connect/certs
