#debug: true
keycloak:
  realm: mano-realm
  auth-server-url: http://mano-auth:8080/auth/
  ssl-required: external
  resource: mano-vnfm
  credentials:
    secret: 50e312ab-9f12-481e-b6a8-c23e0de21628
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    com.ubiqube.etsi.mano.service.rest.ManoLoggingHandler: WARN
    com:
      ubiqube:
        etsi: DEBUG
    org:
      apache:
        http:
          wire: INFO
        activemq:
          audit: WARN
      elasticsearch:
        client:
          sniff:
            Sniffer: OFF
      hibernate:
        collection:
          spi:
            AbstractPersistentCollection: ERROR
        SQL: INFO
      keycloak: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: INFO
        context: INFO
        http: INFO
        jms: INFO
        security: INFO
        web:
          filter: INFO
          servlet: INFO
          reactive: INFO

management:
  elastic:
    metrics:
      export:
        host: http://mano-es:9200
        index: mano-metrics-nfvo
        index-date-format: yyyy-MM-dd
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

mano:
  config:
    type: nfvo
  election:
    script-path: /tmp/etsi-mano/election/groovy
  frontend-url: http://mano-nfvo:8100/ubi-etsi-mano/sol003
  repository:
    phys-root: /tmp/etsi-mano/repository
  swagger-o-auth2: http://mano-auth:8080/auth/realms/mano-realm/protocol/openid-connect/token

server:
  error:
    whitelabel:
      enabled: false
  port: 8100
  servlet:
    contextPath: /ubi-etsi-mano

spring:
  application:
    name: mano-nfvo
  artemis:
    broker-url: tcp://mano-artemis:61616
    user: artemis
    password: simetraehcapa
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://mano-db/mano_nfvo?ApplicationName=NFVO
    username: mano_nfvo
    password: mano
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 600000
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: NON_NULL
    generator:
      ignore-unknown: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent-output: true
      write-empty-json-arrays: false
  jmx:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mvc:
    log-request-details: true
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

springdoc:
  enable-data-rest: false

